apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: 
  labels:
spec:
  acme:
    email: 
    server: 
    privateKeySecretRef:
      name: cloudflare-cluster-issuer-private-key-secret
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: -cloudflare
              key: api-token
