apiVersion: v2
name: cert-manager-install
description: |
  A Helm chart for installing and configuring cert-manager
  in my home lab environment using Cloudflare, Lets Encrypt
  and the ACME DNS01 challenge Cluster Issuer.
type: application
version: 0.1.2
appVersion: "v1.8.2"
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.8.2
    condition: cert-manager.enabled
